name: Go

on:
  push:
    branches: [ "main", "test" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/vanilla-arm/pico:dev

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install build dependencies
      run: |
        dpkg --add-architecture arm64
        apt update
        apt install -y gcc xorg-dev gcc-aarch64-linux-gnu libgl-dev:arm64 libxcursor-dev:arm64 libxi-dev:arm64 libxinerama-dev:arm64 libxrandr-dev:arm64 libxxf86vm-dev:arm64

    - name: Build
      run: |
        go build -o vanilla-tools/ ./...
        tar -czvf vanilla-tools-amd64.tar.gz vanilla-tools/*
        GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc go build -o vanilla-tools/ ./...
        tar -czvf vanilla-tools-arm64.tar.gz vanilla-tools/*

    - name: Calculate and Save Checksums
      run: sha256sum vanilla-tools*.tar.gz >> checksums.txt

    - uses: actions/upload-artifact@v4
      with:
        name: vanilla-tools
        path: |
          checksums.txt
          vanilla-tools*.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          checksums.txt
          vanilla-tools*.tar.gz
